/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.net.Socket;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import modules.IOFile;
import modules.Prime;
import modules.Vigenere;
import tcp.Server;

/**
 *
 * @author letan
 */
public class MainServerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainServerFrame
     */
    
    private static Server runServer;
    private static String key = "abc";
    
    public MainServerFrame() {
        
        initComponents();
        txtKey.setText(key);
        
        try {
            runServer = new Server();
            
            new Thread(new Runnable() {
                @Override
                public void run() {
                    
                    try {
                        
                        while(true){
                            Socket client = runServer.getServer().accept();
                            runServer.acceptClient(client);
                            
                            String sig = runServer.revData();
//                            System.out.println("Sig: "+sig);

                            switch(sig){
                                case "test":
                                    runServer.sendData("success");
                                    break;
                                case "content":
                                    String input = runServer.revData();
                                    String fileName = runServer.revData();
                                    String filePath = "src/main/java/files/"+fileName;

//                                    if(IOFile.isFileExist(filePath)){
//                                        runServer.sendData("fileexist");
//                                        break;
//                                    }
                                    if(!chkByte.isSelected()){
                                        IOFile.saveFileCharacterStream(filePath, Vigenere.encrypt(input, key));
                                    }
                                    else{
                                        IOFile.saveFileByteStream(filePath, Vigenere.encrypt(input, key));
                                    }
                                    runServer.sendData("createdfile");
                                    if(!chkByte.isSelected()){
                                        runServer.sendData(IOFile.convertFromList(Prime.findPrimeInArray(IOFile.convertFromString(Vigenere.decrypt(IOFile.readFileCharacterStream(filePath), key)))));
                                    }
                                    else{
                                        runServer.sendData(IOFile.convertFromList(Prime.findPrimeInArray(IOFile.convertFromString(Vigenere.decrypt(IOFile.readFileByteStream(filePath), key)))));
                                    }

                                    break;
                            }
                            
                            client.close();
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(MainServerFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }).start();
            
        } catch (IOException ex) {
            Logger.getLogger(MainServerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        btnUpdateKey = new javax.swing.JButton();
        chkByte = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Xử Lý");

        jLabel2.setText("Key");

        btnUpdateKey.setText("Cập nhật");
        btnUpdateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKeyActionPerformed(evt);
            }
        });

        chkByte.setText("Byte Stream");
        chkByte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkByteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkByte)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKey, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateKey)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkByte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKeyActionPerformed
        // TODO add your handling code here:
        key = txtKey.getText();
    }//GEN-LAST:event_btnUpdateKeyActionPerformed

    private void chkByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkByteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkByteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainServerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainServerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateKey;
    private javax.swing.JCheckBox chkByte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables
}
